[package]
name = "stateflow-trans-ext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
netsblox-stateflow = "0.1.0"
netsblox-extension-macro = "0.1.0"
netsblox-extension-util = "0.2.4"
wasm-bindgen = "0.2.92"
js-helpers = "0.1.1"
getrandom = { version = "0.2.15", features = ["js"] }

[build-dependencies]
netsblox-extension-util = "0.2.4"
