[package]
name = "stateflow-trans-ext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stateflow-trans = { path = "../stateflow-trans" }
netsblox-extension-macro = { path = "../../netsblox-extension-rs/netsblox-extension-macro" }
netsblox-extension-util = { path = "../../netsblox-extension-rs/netsblox-extension-util" }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["console"] }
getrandom = { version = "0.2.15", features = ["js"] }

[build-dependencies]
netsblox-extension-util = { path = "../../netsblox-extension-rs/netsblox-extension-util" }